services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend/
    image: gipocode/weather-backend:latest
    container_name: backend
    expose:
      - 8000
    restart: always
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend/
    image: gipocode/weather-frontend:latest
    container_name: frontend
    expose:
      - 80
    restart: always
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    image: gipocode/weather-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always