apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployments/weather-backend-deployment.yaml
  - deployments/weather-frontend-deployment.yaml
  - deployments/weather-nginx-deployment.yaml
  - services/weather-backend-service.yaml
  - services/weather-frontend-service.yaml
  - services/weather-nginx-service.yaml